config/routes.rb
Rails.application.routes.draw do
 

  get '/signup' => 'users#new', as: :signup 
  resources :users

  get '/login' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout
  resources :sessions

  get '/wordnik' => 'wordnik#index'
  post '/wordnik' => 'wordnik#create'

  post '/flashcards' => 'flashcards#create' , as: :flashcard 
  resources :flashcards  

  root to: 'application#index'
end
 

app/models/flashcard.rb
class Flashcard
  include Mongoid::Document

	belongs_to :user
  validates :user_id, presence: true
	validates :word, presence: true
	field :word, type: String
	field :examples, type: String
	field :definition, type: String

end

app/models/user.rb
class User

  include Mongoid::Document
  include ActiveModel::SecurePassword
  has_many :flashcards
  field :username, type: String
  field :email, type: String
  field :password_digest, type: String
  has_secure_password
  validates :password, length: { minimum: 5}
  validates :username, presence: true, length: { maximum: 15 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  
end

app/models/wordnik.rb
class Wordnik
  include Mongoid::Document

validate :valid_entry
validates :word, :presence => true

  # responses from Wordnik API
  def self.get_definitions(word)
    query = {api_key: "a2a73e7b926c924fad7001ca3111acd55af2ffabf50eb4ae5", limit: 1, 
    sourceDictionaries: "ahd"} 
    response = HTTParty.get "http://api.wordnik.com:80/v4/word.json/#{word}/definitions?includeRelated=true&useCanonical=false&includeTags=false", query: query
    return response
  end

  def self.get_examples(word)
    query = {api_key: "a2a73e7b926c924fad7001ca3111acd55af2ffabf50eb4ae5", limit: 1}
    response = HTTParty.get "http://api.wordnik.com:80/v4/word.json/#{word}/examples?includeDuplicates=false&useCanonical=false", query: query
    return response
  end

  def valid_entry
    # shows error if user didn't enter a word
    if word.blank?
      errors.add(:word, "Please enter a word.")
    # shows error if word is not a valid entry and/or doesn't exist in database
    elsif !Word.exists?(word: word) && Wordnik.word.get_definitions(word).empty?
      errors.add(:word, "Sorry, no information for #{word}.")
    end
  end

  def upcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    flash[:warning] = "You must be logged in to access that content."
  	redirect_to '/login' unless current_user
  end
end


  # def initialize_wordnik(options={})
  #     options.merge!({:api_key=>ENV['ecf11c4c47818e7ccc4050ae67c0ce0afe2eb985bb5fbc8b4']})
  #     @wordnik = Wordnik::Wordnik.new(options)
  # end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController

	def index
		@flashcards = Flashcard.all
	end	

	# def show
	# 	@flashcard = Flashcard.find(params[:id])
	# end

	def new 
	end

	def create
		@flashcard = current_user.flashcards.new(flashcard_params)
		if @flashcard.save 

			#if the flashcard is saved successfully, add to list of all user's flashcards and redirect to user profile
			redirect_to user_path(current_user.id)
		else
			render :new
		end
	end

	def edit
		@flashcard = Flashcard.find(params[:id])
	end

	def update
		@flashcard = Flashcard.find(params[:id])

		if @flashcard.update(flashcard_params)
			redirect_to flashcards_path
		else
			render :edit
		end
	end

	private

	def flashcard_params
		params.require(:flashcard).permit(:word, :examples, :definition)
	end
end

	

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(username: params[:user][:username]) 
		if user && user.authenticate(params[:user][:password])
			session[:user_id] = user.id.to_s 
			redirect_to user_path(current_user.id)
		else
			flash.now[:danger] = "Username or password incorrect."
			@login = false
			redirect_to root_path, flash: { login_modal: true }
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def index
	end

	def new
		@user = User.new
		redirect_to flashcards_path if current_user
	end


	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id.to_s 
			redirect_to flashcards_path
		else
			flash.now[:danger] = "Invalid form."
			@signup = false
			redirect_to root_path, flash: { manifesto_modal: true }
		end
	end

	def show
		@user = User.find(params[:id])
		@flashcards = @user.flashcards(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

private
	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end
end

app/controllers/wordnik_controller.rb
class WordnikController < ApplicationController
# before_filter :authorize

  def index
    @word_definitions    = Wordnik.get_definitions(params[:word])
    @word_examples       = Wordnik.get_examples(params[:word])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/application/index.html.erb
<!-- Landing Page with everything below the navigation bar -->
<% if flash[:manifesto_modal] %>
<script>
 $('#basicModal').modal('show');
</script>
<% end %>

<% if flash[:login_modal] %>
<script>
 $('#login-basicModal').modal('show');
</script>
<% end %>

<div class="col-md-12 landing-page-container">
  <div class="title">
    <h1>simply&nbsp;vocab</h1>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="explanation row">
  <h3>Why is simply vocab a great choice for your learning needs?</h3><br>
    <div class="col-sm-4 container">
      <p class="circle"><span>It's handy; the flashcards can be accessed on your phone, your tablet, or your computer</span></p>
    </div>  
    <div class="col-sm-4 container">
      <p class="circle"><span>It teaches REAL, everyday English - not a watered-down, simplified version</span></p>
    </div>
    <div class="col-sm-4 container">
      <p class="circle"><span>It's a time - saver;  we make the flashcards so you don't have to</span></p> 
    </div>
<br>
<br>
<br>
<br>
<br> 
<br>
<br>   
</div>
 

app/views/flashcards/index.html.erb
<div class="all-user-flashcard-row">  
  <h3 class="all-user-flashcards">All User Flashcards</h3>
  <br>
  <p>Take a step toward increasing your vocabulary. Create your own flashcards!&nbsp;&nbsp;&nbsp;<%= link_to 'New flashcard', new_flashcard_path %></p>
  <div class="row">
    <div class="col-md-8 col-md-offset-2 list-container">
      <table class="table table-striped">
      <br>
      <thead>
        <tr>
          <th>WORDS</th>
          <th>EXAMPLES</th> 
          <th>DEFINITIONS</th>
        </tr>
      </thead>  
        <tbody>  
          <% @flashcards.each do |flashcard| %>
            <tr>
              <td width="20%"><%= flashcard.word %></td>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <td width="30%"><%= flashcard.examples %></td>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <td width="50%"><%= flashcard.definition %></td>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </tr>
          <% end %> 
        </tbody> 
      </table>
      <br>
      <br>
      <br>
      <br>
      <br>
    </div>
  </div>
</div>

app/views/flashcards/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-5 search-container">
    <div class="create_flashcard">
        <%= form_tag('/wordnik', :method=>'get') do %>
          <br>
          <br>
          <br>
          <br>
          <br>
          <h3>Word Search:</h3> 
          <br>
          <%= text_field_tag('word') %>
          <%= submit_tag('Search') %>
        <% end %>
    </div>
  </div>
</div>

app/views/flashcards/show.html.erb
<div class="individual-card container">
  <% if current_user %>  
  <p><%= @flashcard.word %></p>
  <p><%= @flashcard.examples %></p><br>
  <p><%= @flashcard.definitions %></p><br>

  <% else %>
  <%= link_to "Back to my flashcards", flashcards_path %>
  <%= link_to "Create a new flashcard", new_flashcard_path %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
</small>
<nav>
<ul>
<p class="wordnik-api">WORDNIK Api</p>
<div class="icon">

</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <ul class="nav navbar-nav navbar-left">
      <a class="navbar-brand" href="/">simply vocab</a>
      <% if current_user %>
        <li><p class="welcome">Welcome, <strong><%= current_user.username %></strong></p></li>
        <li class="link"><%= link_to "My Flashcards", user_path(current_user.id) %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <div class="input-group createlogout-btn navbar-right">
          <div class="">
            <div>
              <a type="button" class="btn btn-primary navbar-btn navbar-right-create" href="">Create Flashcards</a>
              <a type="button" class="btn btn-primary navbar-btn navbar-right" href="/logout">Log Out</a>
            </div>
          </div>
        </div>
      <% else %>
        <div class="input-group signuplogin-btn navbar-right">
          <div class="">
            <div>
              <a type="button" class="btn btn-primary signup-navbar-btn" href="#" data-toggle="modal" data-target="#basicModal">Sign Up</a>&nbsp;&nbsp;
              <%= render 'users/user_modal' %>
              <a type="button" class="btn btn-primary login-navbar-btn" href="#" data-toggle="modal" data-target="#login-basicModal">Log In</a>
              <%= render 'sessions/login_modal' %>
            </div>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
</div>

        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head> 
  <title>Simply Vocab</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>
<body>
  <%= render "layouts/navbar" %>
  <%= yield %> 

</body>
</html>

app/views/shared/_error_messages.html.erb
<div class="notice">
  <p>
    <% flash.each do |key, msg| %>
      <%= msg %>
      <br>
    <% end %>
  </p>
</div>

app/views/users/_form.html.erb
<div class="user-new">
  <% flash.each do |key, value| %>
  <div class='alert alert-<%= key %>' role='alert'>
    <%= value %>
  </div>
<% end %>

  <%= form_for User.new do |f| %>
    <%= f.text_field :username, placeholder: "username", class: 'form-control' %>
    <br><br>
    <%= f.text_field :email, placeholder: "email", class: 'form-control' %>
    <br><br>
    <%= f.password_field :password, placeholder: "password", class: 'form-control' %>
    <br><br>
    <%= f.password_field :password_confirmation, placeholder: "confirm password", class: 'form-control' %>
    <br>
    <br>
    <%=f.submit "SIGN UP", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/_user_modal.html.erb
<div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <legend class="user-modal-title signup-legend" id="myModalLabel">Sign Up</legend>
      </div>
      <div class="modal-body">
        <%= render 'users/form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile here</h1>

<div class="row">

	<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>

	<%= f.label :username %>
	<%= f.text_field :username, class: 'form-control' %>
	<br>
	<%= f.label :email %>
	<%= f.password_field :email, class: 'form-control' %>
	<br>
	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>
	<br>
	<%= f.label :password_confirmation, "Confirmation" %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>
	<br>
	<%= f.submit "Save changes", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/users/new.html.erb
<%= render 'users/form' %>

   


   

app/views/users/show.html.erb
<!-- User Profile Page with all user's flashcards -->
<br>
<br>
<br>

<div class="show-profile">
  <p class="hello"><span>hello,</span> <%= current_user.username.upcase %>!</p>
  <div class="link"><%= link_to 'Create a new flashcard', new_flashcard_path %></div>
  <hr class="divider-horizontal"/>
</div>

<div class="show-flashcards">
  <h3>My Flashcards</h3>
  <div class="flashcard-columns">
    <% if current_user.flashcards %>
      <% current_user.flashcards.each do |u| %>
        <div class="flip">
          <div class="card">
            <div class="face front">
              <p><%= u.word %></p>
            </div> 
            <div class="face back">  
              <h4>EXAMPLE:<br><br>

                <%= u.examples %>
              </h4>
              <br>
              <br>
              <h4>DEFINITION:<br><br>
                
                <%= u.definition %>
              </h4>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>


 

app/views/wordnik/index.html.erb
<br>
<br>
<br>
<br>
<div class="wordnik-container">
  <div class="row">
    <div class="col-md-6 col-md-offset-6 text">
      <% if @word_definitions.empty? %>
        <p>Sorry, we could not find that word. Check spelling, and try again.</p> 
        <%= link_to 'New flashcard', new_flashcard_path %>
      <% else %>
        <h3><strong><%= @word_definitions[0]["word"] %></strong></h3>
        <hr/>
        <br>
        <br> 
        <p>EXAMPLE:</p>    
        <p><%= @word_examples["examples"][0]["text"] %></p> 
        <br>
        <p>DEFINITION:</p>
        <p><%= @word_definitions[0]["text"] %></p> 
        <br>
        <%= form_for Flashcard.new() do |f| %>
        <div style ='display:none'>
          <%= f.text_field :word, value: "#{@word_definitions[0]["word"]}" %>
          <%= f.text_field :examples, value: "#{@word_examples["examples"][0]["text"]}" %>
          <%= f.text_field :definition, value: "#{@word_definitions[0]["text"]}" %>
        </div>
          <%= f.submit %>
        <% end %>
      <% end %>
    </div>
  </div>
</div> 